import type { Metadata } from "next";
import PageTransition from "@/components/layout/PageTransition";
import GuildClient from "@/components/guild/GuildClient";

export const metadata: Metadata = {
  title: "Guild Hierarchy",
  description: "Meet the Dragon Up guild members, officers, and leaders. Browse our tactical organizational structure and player bios.",
  alternates: { canonical: "/guild" },
};

// ─── FUTURE READY: SWITCHABLE DATA SOURCE ────────────────────────────
// Once Prisma client is fully generated/reconfigured, replace MOCK_MEMBERS
// with: const guildMembers = await db.guildMember.findMany({ where: { isActive: true }, orderBy: { displayOrder: "asc" } });
const MOCK_MEMBERS = [
  // ─── Guild Leader (1) ───
  {
    id: "g-leader",
    uid: "DU-LEADER-01",
    nickname: "GRANDMASTER",
    name: "Aman Sen",
    avatar: "", // Coming soon placeholder
    role: "LEADER",
    status: "ACTIVE",
    level: 75,
    favoriteGame: "Free Fire",
    signatureWeapon: "M1887 (Double Barrel)",
    favoriteCharacter: "Alok",
    favoritePet: "Rockie",
    device: "iPad Pro",
    country: "India",
    bio: "The ultimate visionary and original founder of Dragon Up guild. Guiding our squad to esports glory.",
    mvpCount: 154,
    wins: 1240,
    matches: 1850,
    youtube: "https://youtube.com/@dragonup",
    instagram: "",
    discord: "https://discord.gg/dragonup",
    displayOrder: 1,
    isActive: true,
    joinedAt: "2025-01-10T12:00:00.000Z",
    createdAt: "2025-01-10T12:00:00.000Z",
    updatedAt: "2025-01-10T12:00:00.000Z",
  },
  // ─── Acting Guild Leader (1) ───
  {
    id: "g-acting-leader",
    uid: "DU-ACTING-01",
    nickname: "ZORO",
    name: "Zoro Acting Leader",
    avatar: "/images/team/Players_assests/Zoro_acting_leader.png",
    role: "ACTING_LEADER",
    status: "ACTIVE",
    level: 72,
    favoriteGame: "Free Fire",
    signatureWeapon: "MP40 (Flashing Spade)",
    favoriteCharacter: "Chrono",
    favoritePet: "Beaston",
    device: "iPhone 15 Pro Max",
    country: "India",
    bio: "Taking care of daily guild operations, scrim matches, tournaments, and squad administration.",
    mvpCount: 128,
    wins: 980,
    matches: 1420,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 2,
    isActive: true,
    joinedAt: "2025-02-15T12:00:00.000Z",
    createdAt: "2025-02-15T12:00:00.000Z",
    updatedAt: "2025-02-15T12:00:00.000Z",
  },
  // ─── Guild Officers (4) ───
  {
    id: "g-officer-01",
    uid: "DU-OFFICER-01",
    nickname: "ZORO SQUAD",
    name: "Zoro Officer",
    avatar: "/images/team/Guild_Officers/Zoro_officer.png",
    role: "OFFICER",
    status: "ACTIVE",
    level: 68,
    favoriteGame: "Free Fire",
    signatureWeapon: "AWM (Duke Swallowtail)",
    favoriteCharacter: "K",
    favoritePet: "Dreki",
    device: "ROG Phone 8",
    country: "India",
    bio: "Head tournament coordinator and squad manager. Specializes in long-range sniping cover.",
    mvpCount: 88,
    wins: 620,
    matches: 980,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 3,
    isActive: true,
    joinedAt: "2025-03-01T12:00:00.000Z",
    createdAt: "2025-03-01T12:00:00.000Z",
    updatedAt: "2025-03-01T12:00:00.000Z",
  },
  {
    id: "g-officer-02",
    uid: "DU-OFFICER-02",
    nickname: "CYPHER",
    name: "Sohan Roy",
    avatar: "", // Coming soon placeholder
    role: "OFFICER",
    status: "ACTIVE",
    level: 66,
    favoriteGame: "Free Fire",
    signatureWeapon: "Groza",
    favoriteCharacter: "Wukong",
    favoritePet: "Mr. Waggor",
    device: "iPhone 14 Pro",
    country: "India",
    bio: "Lead recruiter and tactician. Responsible for vetting new players and mapping match rotations.",
    mvpCount: 74,
    wins: 510,
    matches: 890,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 4,
    isActive: true,
    joinedAt: "2025-03-10T12:00:00.000Z",
    createdAt: "2025-03-10T12:00:00.000Z",
    updatedAt: "2025-03-10T12:00:00.000Z",
  },
  {
    id: "g-officer-03",
    uid: "DU-OFFICER-03",
    nickname: "VALKYRIE",
    name: "Riya Sharma",
    avatar: "", // Coming soon placeholder
    role: "OFFICER",
    status: "ACTIVE",
    level: 65,
    favoriteGame: "Free Fire",
    signatureWeapon: "SCAR (Megashark)",
    favoriteCharacter: "Kelly",
    favoritePet: "Falco",
    device: "iPad Mini 6",
    country: "India",
    bio: "Community moderator and team manager. Ensuring high-energy operations during live community custom rooms.",
    mvpCount: 65,
    wins: 490,
    matches: 850,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 5,
    isActive: true,
    joinedAt: "2025-03-15T12:00:00.000Z",
    createdAt: "2025-03-15T12:00:00.000Z",
    updatedAt: "2025-03-15T12:00:00.000Z",
  },
  {
    id: "g-officer-04",
    uid: "DU-OFFICER-04",
    nickname: "PHOENIX",
    name: "Nikhil Das",
    avatar: "", // Coming soon placeholder
    role: "OFFICER",
    status: "ON_BREAK",
    level: 64,
    favoriteGame: "Free Fire",
    signatureWeapon: "M4A1",
    favoriteCharacter: "Hayato",
    favoritePet: "Ottero",
    device: "Samsung S23 Ultra",
    country: "India",
    bio: "Esports analyst and assistant coach. Helps review VOD files for tournament tactics.",
    mvpCount: 52,
    wins: 420,
    matches: 790,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 6,
    isActive: true,
    joinedAt: "2025-04-01T12:00:00.000Z",
    createdAt: "2025-04-01T12:00:00.000Z",
    updatedAt: "2025-04-01T12:00:00.000Z",
  },
  // ─── Guild Players (18) ───
  {
    id: "g-player-01",
    uid: "DU-PLAYER-01",
    nickname: "CHINTU",
    name: "Chintu Guild Player",
    avatar: "/images/team/Players_assests/Chintu_Guild_Player.png",
    role: "PLAYER",
    status: "ACTIVE",
    level: 62,
    favoriteGame: "Free Fire",
    signatureWeapon: "M1014",
    favoriteCharacter: "Alok",
    favoritePet: "Flash",
    device: "iPhone 13 Pro",
    country: "India",
    bio: "Aggressive front-line rusher. Specializes in close-range shotguns battles.",
    mvpCount: 58,
    wins: 380,
    matches: 650,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 7,
    isActive: true,
    joinedAt: "2025-04-10T12:00:00.000Z",
    createdAt: "2025-04-10T12:00:00.000Z",
    updatedAt: "2025-04-10T12:00:00.000Z",
  },
  {
    id: "g-player-02",
    uid: "DU-PLAYER-02",
    nickname: "K H S52440",
    name: "K.H.S5244Q Guild Player",
    avatar: "/images/team/Players_assests/K.H.S5244Q_Guild_Player.png",
    role: "PLAYER",
    status: "ACTIVE",
    level: 61,
    favoriteGame: "Free Fire",
    signatureWeapon: "Woodpecker",
    favoriteCharacter: "Moco",
    favoritePet: "Detective Panda",
    device: "OnePlus 11",
    country: "India",
    bio: "Tactical support and mid-range marksman cover coordinator.",
    mvpCount: 42,
    wins: 310,
    matches: 580,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 8,
    isActive: true,
    joinedAt: "2025-04-12T12:00:00.000Z",
    createdAt: "2025-04-12T12:00:00.000Z",
    updatedAt: "2025-04-12T12:00:00.000Z",
  },
  {
    id: "g-player-03",
    uid: "DU-PLAYER-03",
    nickname: "SHADOW",
    name: "Vikram Malhotra",
    avatar: "", // Coming soon placeholder
    role: "PLAYER",
    status: "ACTIVE",
    level: 59,
    favoriteGame: "Free Fire",
    signatureWeapon: "MP5",
    favoriteCharacter: "Homer",
    favoritePet: "Zasil",
    device: "Poco F5",
    country: "India",
    bio: "Flanker and stealth specialist. Excellent at maps positioning.",
    mvpCount: 39,
    wins: 290,
    matches: 540,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 9,
    isActive: true,
    joinedAt: "2025-04-15T12:00:00.000Z",
    createdAt: "2025-04-15T12:00:00.000Z",
    updatedAt: "2025-04-15T12:00:00.000Z",
  },
  {
    id: "g-player-04",
    uid: "DU-PLAYER-04",
    nickname: "VIPER",
    name: "Abhinav Singh",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 58,
    favoriteGame: "Free Fire",
    signatureWeapon: "M82B (Sniper)",
    favoriteCharacter: "Rafael",
    favoritePet: "Night Panther",
    device: "iPad Pro",
    country: "India",
    bio: "Silent sniper cover support. Specializes in wall-penetration shots.",
    mvpCount: 48,
    wins: 340,
    matches: 610,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 10,
    isActive: true,
    joinedAt: "2025-04-20T12:00:00.000Z",
    createdAt: "2025-04-20T12:00:00.000Z",
    updatedAt: "2025-04-20T12:00:00.000Z",
  },
  {
    id: "g-player-05",
    uid: "DU-PLAYER-05",
    nickname: "RAPTOR",
    name: "Rahul Verma",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 57,
    favoriteGame: "Free Fire",
    signatureWeapon: "FAMAS",
    favoriteCharacter: "Luqueta",
    favoritePet: "Spirit Fox",
    device: "iPhone 14",
    country: "India",
    bio: "Consistent mid-range rifleman. Holds defensive lines during custom games.",
    mvpCount: 29,
    wins: 260,
    matches: 510,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 11,
    isActive: true,
    joinedAt: "2025-04-22T12:00:00.000Z",
    createdAt: "2025-04-22T12:00:00.000Z",
    updatedAt: "2025-04-22T12:00:00.000Z",
  },
  {
    id: "g-player-06",
    uid: "DU-PLAYER-06",
    nickname: "NOVA",
    name: "Pooja Hegde",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 56,
    favoriteGame: "Free Fire",
    signatureWeapon: "Thompson",
    favoriteCharacter: "Steffie",
    favoritePet: "Moony",
    device: "iPad Air",
    country: "India",
    bio: "Support utility and team coordinator. Specializes in defensive walls placements.",
    mvpCount: 22,
    wins: 215,
    matches: 480,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 12,
    isActive: true,
    joinedAt: "2025-05-01T12:00:00.000Z",
    createdAt: "2025-05-01T12:00:00.000Z",
    updatedAt: "2025-05-01T12:00:00.000Z",
  },
  {
    id: "g-player-07",
    uid: "DU-PLAYER-07",
    nickname: "TITAN",
    name: "Kabir Khan",
    avatar: "",
    role: "PLAYER",
    status: "ON_BREAK",
    level: 56,
    favoriteGame: "Free Fire",
    signatureWeapon: "Groza",
    favoriteCharacter: "Kenta",
    favoritePet: "Fang",
    device: "ROG Phone 7",
    country: "India",
    bio: "Frontline vanguard shielding the squad during matches rotations.",
    mvpCount: 27,
    wins: 230,
    matches: 490,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 13,
    isActive: true,
    joinedAt: "2025-05-05T12:00:00.000Z",
    createdAt: "2025-05-05T12:00:00.000Z",
    updatedAt: "2025-05-05T12:00:00.000Z",
  },
  {
    id: "g-player-08",
    uid: "DU-PLAYER-08",
    nickname: "ZEUS",
    name: "Arjun Mehta",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 55,
    favoriteGame: "Free Fire",
    signatureWeapon: "M60",
    favoriteCharacter: "Xayne",
    favoritePet: "Finn",
    device: "Samsung S22",
    country: "India",
    bio: "LMG specialist providing suppression cover fire during pushes.",
    mvpCount: 31,
    wins: 245,
    matches: 520,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 14,
    isActive: true,
    joinedAt: "2025-05-10T12:00:00.000Z",
    createdAt: "2025-05-10T12:00:00.000Z",
    updatedAt: "2025-05-10T12:00:00.000Z",
  },
  {
    id: "g-player-09",
    uid: "DU-PLAYER-09",
    nickname: "GHOST",
    name: "Siddharth Sen",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 54,
    favoriteGame: "Free Fire",
    signatureWeapon: "UMP",
    favoriteCharacter: "Tatsuya",
    favoritePet: "Kactus",
    device: "iPhone 13",
    country: "India",
    bio: "Highly mobile entries rusher, utilizing flanking routes.",
    mvpCount: 35,
    wins: 210,
    matches: 460,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 15,
    isActive: true,
    joinedAt: "2025-05-12T12:00:00.000Z",
    createdAt: "2025-05-12T12:00:00.000Z",
    updatedAt: "2025-05-12T12:00:00.000Z",
  },
  {
    id: "g-player-10",
    uid: "DU-PLAYER-10",
    nickname: "SIREN",
    name: "Ananya Sen",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 53,
    favoriteGame: "Free Fire",
    signatureWeapon: "MP40",
    favoriteCharacter: "Dasha",
    favoritePet: "Poring",
    device: "OnePlus 10R",
    country: "India",
    bio: "Aggressive secondary support rusher, backing entry fraggers.",
    mvpCount: 20,
    wins: 180,
    matches: 420,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 16,
    isActive: true,
    joinedAt: "2025-05-15T12:00:00.000Z",
    createdAt: "2025-05-15T12:00:00.000Z",
    updatedAt: "2025-05-15T12:00:00.000Z",
  },
  {
    id: "g-player-11",
    uid: "DU-PLAYER-11",
    nickname: "APEX",
    name: "Rohan Kapoor",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 53,
    favoriteGame: "Free Fire",
    signatureWeapon: "AUG",
    favoriteCharacter: "A124",
    favoritePet: "Rockie",
    device: "Realme GT",
    country: "India",
    bio: "Utility operator deploying tactical devices and layout configurations.",
    mvpCount: 18,
    wins: 190,
    matches: 440,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 17,
    isActive: true,
    joinedAt: "2025-05-20T12:00:00.000Z",
    createdAt: "2025-05-20T12:00:00.000Z",
    updatedAt: "2025-05-20T12:00:00.000Z",
  },
  {
    id: "g-player-12",
    uid: "DU-PLAYER-12",
    nickname: "HUNTER",
    name: "Manish Nair",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 52,
    favoriteGame: "Free Fire",
    signatureWeapon: "M14",
    favoriteCharacter: "Shirou",
    favoritePet: "Sensei Tig",
    device: "iPhone 12 Pro",
    country: "India",
    bio: "Mid-range counter sniper providing critical callouts and damage tracking.",
    mvpCount: 23,
    wins: 170,
    matches: 410,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 18,
    isActive: true,
    joinedAt: "2025-05-25T12:00:00.000Z",
    createdAt: "2025-05-25T12:00:00.000Z",
    updatedAt: "2025-05-25T12:00:00.000Z",
  },
  {
    id: "g-player-13",
    uid: "DU-PLAYER-13",
    nickname: "ECLIPSE",
    name: "Karan Johar",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 52,
    favoriteGame: "Free Fire",
    signatureWeapon: "Woodpecker",
    favoriteCharacter: "Santino",
    favoritePet: "Hoot",
    device: "Nothing Phone 1",
    country: "India",
    bio: "Highly adaptative support player filling squad gaps during rounds.",
    mvpCount: 16,
    wins: 155,
    matches: 390,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 19,
    isActive: true,
    joinedAt: "2025-06-01T12:00:00.000Z",
    createdAt: "2025-06-01T12:00:00.000Z",
    updatedAt: "2025-06-01T12:00:00.000Z",
  },
  {
    id: "g-player-14",
    uid: "DU-PLAYER-14",
    nickname: "KRAKEN",
    name: "Gaurav Malhotra",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 51,
    favoriteGame: "Free Fire",
    signatureWeapon: "AK47",
    favoriteCharacter: "Ignis",
    favoritePet: "Pug",
    device: "iQOO 9 Pro",
    country: "India",
    bio: "High recoil weapon control fragger, specializing in assault rifles headshots.",
    mvpCount: 22,
    wins: 162,
    matches: 380,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 20,
    isActive: true,
    joinedAt: "2025-06-05T12:00:00.000Z",
    createdAt: "2025-06-05T12:00:00.000Z",
    updatedAt: "2025-06-05T12:00:00.000Z",
  },
  {
    id: "g-player-15",
    uid: "DU-PLAYER-15",
    nickname: "SPECTER",
    name: "Sunil Dutt",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 51,
    favoriteGame: "Free Fire",
    signatureWeapon: "VSS",
    favoriteCharacter: "Iris",
    favoritePet: "Lutra",
    device: "Xiaomi 12 Pro",
    country: "India",
    bio: "Long-range support chip-damage dealer, pressuring opponents behind walls.",
    mvpCount: 14,
    wins: 148,
    matches: 360,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 21,
    isActive: true,
    joinedAt: "2025-06-10T12:00:00.000Z",
    createdAt: "2025-06-10T12:00:00.000Z",
    updatedAt: "2025-06-10T12:00:00.000Z",
  },
  {
    id: "g-player-16",
    uid: "DU-PLAYER-16",
    nickname: "VALOR",
    name: "Deepak Chawla",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 50,
    favoriteGame: "Free Fire",
    signatureWeapon: "M4A1",
    favoriteCharacter: "Wukong",
    favoritePet: "Beaston",
    device: "iPhone 11 Pro",
    country: "India",
    bio: "Secondary vanguard assisting in holding positions during final zones.",
    mvpCount: 17,
    wins: 154,
    matches: 370,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 22,
    isActive: true,
    joinedAt: "2025-06-12T12:00:00.000Z",
    createdAt: "2025-06-12T12:00:00.000Z",
    updatedAt: "2025-06-12T12:00:00.000Z",
  },
  {
    id: "g-player-17",
    uid: "DU-PLAYER-17",
    nickname: "OBLIVION",
    name: "Preet Singh",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 50,
    favoriteGame: "Free Fire",
    signatureWeapon: "MP40",
    favoriteCharacter: "Sonia",
    favoritePet: "Yeti",
    device: "OnePlus Nord",
    country: "India",
    bio: "Assists in flanking operations and setting up ambush zones.",
    mvpCount: 12,
    wins: 130,
    matches: 320,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 23,
    isActive: true,
    joinedAt: "2025-06-15T12:00:00.000Z",
    createdAt: "2025-06-15T12:00:00.000Z",
    updatedAt: "2025-06-15T12:00:00.000Z",
  },
  {
    id: "g-player-18",
    uid: "DU-PLAYER-18",
    nickname: "NEXUS",
    name: "Amit Singhal",
    avatar: "",
    role: "PLAYER",
    status: "ACTIVE",
    level: 50,
    favoriteGame: "Free Fire",
    signatureWeapon: "Bizon",
    favoriteCharacter: "Orion",
    favoritePet: "Kactus",
    device: "Redmi Note 12",
    country: "India",
    bio: "Aggressive support rusher helping entries during critical squad fights.",
    mvpCount: 15,
    wins: 140,
    matches: 340,
    youtube: "",
    instagram: "",
    discord: "",
    displayOrder: 24,
    isActive: true,
    joinedAt: "2025-06-20T12:00:00.000Z",
    createdAt: "2025-06-20T12:00:00.000Z",
    updatedAt: "2025-06-20T12:00:00.000Z",
  },
];

export default async function GuildPage() {
  const members = MOCK_MEMBERS.map((m) => ({
    ...m,
  }));

  return (
    <PageTransition>
      <GuildClient initialMembers={members as any} />
    </PageTransition>
  );
}
