import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "node:path";

const dbPath = path.join(process.cwd(), "prisma", "dev.db");
const dbUrl = process.env.DATABASE_URL ?? `file:${dbPath}`;

const adapter = new PrismaBetterSqlite3({
  url: dbUrl,
});

const prisma = new PrismaClient({
  adapter,
});

async function main() {
  console.log("🐉 Seeding Dragon Up database...");

  // ─── Admin User ─────────────────────────────────────────────────
  const adminEmail = process.env.ADMIN_EMAIL || "admin@dragonup.com";
  const adminPassword = process.env.ADMIN_PASSWORD || "DragonUp@2025!";
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  await prisma.admin.upsert({
    where: { email: adminEmail },
    update: { passwordHash },
    create: {
      email: adminEmail,
      passwordHash,
    },
  });
  console.log(`✅ Admin user created: ${adminEmail}`);

  // ─── Team Members ──────────────────────────────────────────────
  const teamMembers = [
    {
      name: "Dragon Up Creator",
      role: "Founder & Creator",
      bio: "The visionary behind Dragon Up. Passionate about Free Fire, PC gaming, and building a community where every gamer feels at home.",
      favoriteGame: "Free Fire",
      skills: "Content Creation, Community Building, Gaming Strategy",
      displayOrder: 1,
    },
    {
      name: "Content Manager",
      role: "Content Manager",
      bio: "Responsible for planning, scheduling, and ensuring every video and post meets the Dragon Up quality standard.",
      favoriteGame: "Valorant",
      skills: "Content Strategy, Social Media, Analytics",
      displayOrder: 2,
    },
    {
      name: "Video Editor",
      role: "Video Editor",
      bio: "The creative force behind Dragon Up's cinematic gaming edits, highlights, and montages.",
      favoriteGame: "GTA V",
      skills: "Video Editing, Motion Graphics, Color Grading",
      displayOrder: 3,
    },
    {
      name: "Community Manager",
      role: "Community Manager",
      bio: "The bridge between Dragon Up and the community. Manages events and keeps the energy high.",
      favoriteGame: "Fortnite",
      skills: "Community Engagement, Event Management, Moderation",
      displayOrder: 4,
    },
    {
      name: "Stream Moderator",
      role: "Stream Moderator",
      bio: "Keeps Dragon Up livestreams engaging and safe for all viewers.",
      favoriteGame: "Minecraft",
      skills: "Live Moderation, Viewer Engagement, Stream Management",
      displayOrder: 5,
    },
    {
      name: "Tournament Manager",
      role: "Tournament Manager",
      bio: "Planning and coordinating future competitive events for the Dragon Up community.",
      favoriteGame: "Free Fire",
      skills: "Tournament Organization, Competitive Gaming, Bracket Management",
      displayOrder: 6,
    },
  ];

  for (const member of teamMembers) {
    await prisma.teamMember.upsert({
      where: { id: `seed-${member.displayOrder}` },
      update: member,
      create: {
        id: `seed-${member.displayOrder}`,
        ...member,
        isActive: true,
      },
    });
  }
  console.log(`✅ ${teamMembers.length} team members created`);

  // ─── Site Settings ─────────────────────────────────────────────
  const settings = [
    { key: "site_status", value: "online" },
    { key: "maintenance_message", value: "Dragon Up is currently undergoing maintenance." },
    { key: "last_updated", value: new Date().toISOString() },
  ];

  for (const setting of settings) {
    await prisma.siteSetting.upsert({
      where: { key: setting.key },
      update: { value: setting.value },
      create: setting,
    });
  }
  console.log(`✅ ${settings.length} site settings created`);

  // ─── News Articles (CMS Content) ──────────────────────────────
  const articles = [
    {
      title: "Awakening the Dragon: Free Fire Guide",
      slug: "awakening-the-dragon-free-fire-guide",
      excerpt: "Learn the latest tips and tricks to dominate the battleground in Free Fire.",
      content: "This guide covers the top rank push strategies, character skill combinations (like Alok + Kelly), and HUD sensitivities for perfect headshots.",
      category: "Guides",
      authorName: "Dragon Up Creator",
      status: "PUBLISHED",
      isFeatured: true,
      publishedAt: new Date(),
    },
    {
      title: "PC Gaming vs Mobile Gaming",
      slug: "pc-gaming-vs-mobile-gaming",
      excerpt: "An in-depth analysis of hardware capabilities and performance thresholds.",
      content: "We compare processing core layouts, GPU cooling requirements, and screen refresh rates to understand where the ultimate competitive advantage lies.",
      category: "Opinion",
      authorName: "Content Manager",
      status: "DRAFT",
      isFeatured: false,
    },
    {
      title: "Dragon Up Esports Tournament Announcement",
      slug: "dragon-up-esports-tournament-announcement",
      excerpt: "Get ready for the first community custom room clash squad championship.",
      content: "Registration details, bracket layouts, and prize pools will be announced soon. Form your teams and start practicing now!",
      category: "News",
      authorName: "Tournament Manager",
      status: "DRAFT",
      isFeatured: false,
    }
  ];

  for (let i = 0; i < articles.length; i++) {
    const article = articles[i];
    await prisma.newsArticle.upsert({
      where: { slug: article.slug },
      update: article,
      create: {
        id: `seed-article-${i + 1}`,
        ...article,
      },
    });
  }
  console.log(`✅ ${articles.length} news articles created`);

  // ─── Guild Members ──────────────────────────────────────────────
  const guildMembers = [
    {
      name: "Harsha Vardhan",
      nickname: "DRAGON_BOSS",
      avatar: "/images/team/founder.png",
      uid: "UID-88390210",
      role: "GUILD_LEADER",
      status: "ACTIVE",
      joinedAt: new Date("2023-01-15"),
      favoriteGame: "Free Fire",
      displayOrder: 1,
      isActive: true,
      country: "India",
      about: "The ultimate commander and strategical mastermind of the Dragon Up Guild. Leading with honor, power, and fire.",
      achievements: "Free Fire Top Tier Champion, MVP of Season 15, Community Pioneer",
      rank: "Grandmaster",
      level: 78,
      matchesPlayed: 5400,
      wins: 3820,
      mvpCount: 1200,
      favoriteWeapon: "M1887",
      favoriteCharacter: "Alok",
      favoritePet: "Falco",
      device: "ROG Phone 8 Pro",
      youtube: "https://youtube.com/dragonup",
      instagram: "https://instagram.com/dragonup",
      discord: "https://discord.gg/dragonup",
      facebook: "",
    },
    {
      name: "Anish Roy",
      nickname: "DRACO_COMMANDER",
      avatar: "/images/team/founder.png",
      uid: "UID-99201928",
      role: "ACTING_GUILD_LEADER",
      status: "ACTIVE",
      joinedAt: new Date("2023-03-22"),
      favoriteGame: "Free Fire",
      displayOrder: 2,
      isActive: true,
      country: "India",
      about: "Second in command, responsible for tactical execution and field management. A master of squad combat.",
      achievements: "Squad Leader Excellence Award, 2024 Pro League Finalist",
      rank: "Heroic",
      level: 72,
      matchesPlayed: 4300,
      wins: 2900,
      mvpCount: 850,
      favoriteWeapon: "MP40",
      favoriteCharacter: "Chrono",
      favoritePet: "Zasil",
      device: "iPhone 15 Pro Max",
      youtube: "https://youtube.com/anish",
      instagram: "https://instagram.com/anish",
      discord: "https://discord.gg/dragonup",
      facebook: "",
    },
    // Officers
    {
      name: "Priya Sharma",
      nickname: "SQUAD_QUEEN",
      avatar: "/images/team/founder.png",
      uid: "UID-11223344",
      role: "OFFICER",
      status: "ACTIVE",
      joinedAt: new Date("2023-06-10"),
      favoriteGame: "Free Fire",
      displayOrder: 3,
      isActive: true,
      country: "India",
      about: "Lead recruiter and tactician. Ensures only the most skilled gamers join the rank.",
      achievements: "Top Recruiter 2023, Strategy Guru",
      rank: "Diamond IV",
      level: 65,
      matchesPlayed: 3200,
      wins: 1900,
      mvpCount: 420,
      favoriteWeapon: "AWM",
      favoriteCharacter: "Kelly",
      favoritePet: "Ottero",
      device: "iPad Pro M2",
      youtube: "",
      instagram: "https://instagram.com/priya",
      discord: "",
      facebook: "",
    },
    {
      name: "Rahul Verma",
      nickname: "SHADOW_SNIPER",
      avatar: "/images/team/founder.png",
      uid: "UID-22334455",
      role: "OFFICER",
      status: "ACTIVE",
      joinedAt: new Date("2023-08-01"),
      favoriteGame: "Free Fire",
      displayOrder: 4,
      isActive: true,
      country: "India",
      about: "Sniper expert and trainer. Conducting daily target practices for squad members.",
      achievements: "Headshot Ratio Record Holder (74%)",
      rank: "Heroic",
      level: 69,
      matchesPlayed: 3900,
      wins: 2400,
      mvpCount: 680,
      favoriteWeapon: "Woodpecker",
      favoriteCharacter: "Moco",
      favoritePet: "Rockie",
      device: "Galaxy S24 Ultra",
      youtube: "https://youtube.com/rahul",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Vikram Malhotra",
      nickname: "TITAN_TANK",
      avatar: "/images/team/founder.png",
      uid: "UID-33445566",
      role: "OFFICER",
      status: "ACTIVE",
      joinedAt: new Date("2023-09-15"),
      favoriteGame: "Free Fire",
      displayOrder: 5,
      isActive: true,
      country: "India",
      about: "Frontline rusher. Specializes in close-combat and drawing enemy fire.",
      achievements: "First Blood Specialist, Hard Core Vanguard",
      rank: "Heroic",
      level: 67,
      matchesPlayed: 3500,
      wins: 2100,
      mvpCount: 500,
      favoriteWeapon: "M1014",
      favoriteCharacter: "Wukong",
      favoritePet: "Poring",
      device: "OnePlus 12",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Sneha Patel",
      nickname: "SUPPORT_ANGEL",
      avatar: "/images/team/founder.png",
      uid: "UID-44556677",
      role: "OFFICER",
      status: "ON_BREAK",
      joinedAt: new Date("2023-11-20"),
      favoriteGame: "Free Fire",
      displayOrder: 6,
      isActive: true,
      country: "India",
      about: "Main support and healer. Keeps the squad alive in high-pressure tournaments.",
      achievements: "Most Revives in Tournament Season 3",
      rank: "Diamond III",
      level: 63,
      matchesPlayed: 2800,
      wins: 1550,
      mvpCount: 290,
      favoriteWeapon: "Treatment Sniper",
      favoriteCharacter: "Olivia",
      favoritePet: "Beaston",
      device: "iPhone 14 Pro",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    // Players (8 items)
    {
      name: "Arjun Singh",
      nickname: "BLAZE_OP",
      avatar: "/images/team/founder.png",
      uid: "UID-55667788",
      role: "PLAYER",
      status: "ACTIVE",
      joinedAt: new Date("2024-01-05"),
      favoriteGame: "Free Fire",
      displayOrder: 7,
      isActive: true,
      country: "India",
      about: "Aggressive close-range player with exceptional mechanical reflexes.",
      achievements: "Clash Squad Local Winner",
      rank: "Heroic",
      level: 61,
      matchesPlayed: 2200,
      wins: 1200,
      mvpCount: 310,
      favoriteWeapon: "M1887",
      favoriteCharacter: "Hayato",
      favoritePet: "Tiger",
      device: "iPhone 13 Pro",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Karan Johar",
      nickname: "GHOST_REAPER",
      avatar: "/images/team/founder.png",
      uid: "UID-66778899",
      role: "PLAYER",
      status: "ACTIVE",
      joinedAt: new Date("2024-01-18"),
      favoriteGame: "Free Fire",
      displayOrder: 8,
      isActive: true,
      country: "India",
      about: "Flanker expert who sneaky rushes from behind. High IQ positioning.",
      achievements: "Sneak Attack Master 2024",
      rank: "Platinum V",
      level: 58,
      matchesPlayed: 1800,
      wins: 950,
      mvpCount: 190,
      favoriteWeapon: "Groza",
      favoriteCharacter: "K",
      favoritePet: "Night Panther",
      device: "ROG Phone 6",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Meera Nair",
      nickname: "VALKYRIE_01",
      avatar: "/images/team/founder.png",
      uid: "UID-77889900",
      role: "PLAYER",
      status: "ACTIVE",
      joinedAt: new Date("2024-02-12"),
      favoriteGame: "Free Fire",
      displayOrder: 9,
      isActive: true,
      country: "India",
      about: "Long-range support sniper player. Spotting and cover fire specialist.",
      achievements: "Sharp Shooter Badge",
      rank: "Diamond I",
      level: 59,
      matchesPlayed: 1950,
      wins: 1100,
      mvpCount: 220,
      favoriteWeapon: "AC80",
      favoriteCharacter: "Laura",
      favoritePet: "Waggor",
      device: "iPhone 15",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Deepak Rawat",
      nickname: "BULLET_STORM",
      avatar: "/images/team/founder.png",
      uid: "UID-88990011",
      role: "PLAYER",
      status: "OFFLINE",
      joinedAt: new Date("2024-03-01"),
      favoriteGame: "Free Fire",
      displayOrder: 10,
      isActive: true,
      country: "India",
      about: "SMG expert. Loves to rush with full spray. High fire rate gameplay.",
      achievements: "Spray and Pray Elite",
      rank: "Platinum IV",
      level: 56,
      matchesPlayed: 1600,
      wins: 820,
      mvpCount: 150,
      favoriteWeapon: "Bizon",
      favoriteCharacter: "Dasha",
      favoritePet: "Moony",
      device: "Poco F5",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Ishaan Sen",
      nickname: "PULSE_FIRE",
      avatar: "/images/team/founder.png",
      uid: "UID-99001122",
      role: "PLAYER",
      status: "ACTIVE",
      joinedAt: new Date("2024-03-20"),
      favoriteGame: "Free Fire",
      displayOrder: 11,
      isActive: true,
      country: "India",
      about: "Mid-range assault expert. Perfect grenade launcher placement.",
      achievements: "Grenadier Specialist",
      rank: "Diamond II",
      level: 60,
      matchesPlayed: 2100,
      wins: 1150,
      mvpCount: 260,
      favoriteWeapon: "M60",
      favoriteCharacter: "Alvaro",
      favoritePet: "Beaston",
      device: "OnePlus 11R",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Rohit Shetty",
      nickname: "NIGHTMARE_FF",
      avatar: "/images/team/founder.png",
      uid: "UID-00112233",
      role: "PLAYER",
      status: "ACTIVE",
      joinedAt: new Date("2024-04-10"),
      favoriteGame: "Free Fire",
      displayOrder: 12,
      isActive: true,
      country: "India",
      about: "Close range double vector rusher. Aggressive speed plays.",
      achievements: "Speedster Rusher",
      rank: "Diamond I",
      level: 57,
      matchesPlayed: 1750,
      wins: 900,
      mvpCount: 200,
      favoriteWeapon: "Vector",
      favoriteCharacter: "D-Bee",
      favoritePet: "Pug",
      device: "iPad Mini 6",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Aditi Rao",
      nickname: "CYPHER_GIRL",
      avatar: "/images/team/founder.png",
      uid: "UID-01223344",
      role: "PLAYER",
      status: "ACTIVE",
      joinedAt: new Date("2024-04-25"),
      favoriteGame: "Free Fire",
      displayOrder: 13,
      isActive: true,
      country: "India",
      about: "Strategy caller. High utility item usage (Gloo walls, smoke, flash).",
      achievements: "Tactical Cover Expert",
      rank: "Platinum V",
      level: 55,
      matchesPlayed: 1400,
      wins: 760,
      mvpCount: 130,
      favoriteWeapon: "M4A1",
      favoriteCharacter: "Steffie",
      favoritePet: "Waggor",
      device: "Nothing Phone 2",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    },
    {
      name: "Suresh Raina",
      nickname: "THUNDER_GOD",
      avatar: "/images/team/founder.png",
      uid: "UID-02334455",
      role: "PLAYER",
      status: "OFFLINE",
      joinedAt: new Date("2024-05-02"),
      favoriteGame: "Free Fire",
      displayOrder: 14,
      isActive: true,
      country: "India",
      about: "One-tap headshot player. Prefers desert eagle close combat.",
      achievements: "One-Tap Legend",
      rank: "Heroic",
      level: 63,
      matchesPlayed: 2500,
      wins: 1450,
      mvpCount: 400,
      favoriteWeapon: "Desert Eagle",
      favoriteCharacter: "Rafael",
      favoritePet: "Sensei Tig",
      device: "iPhone 15 Pro",
      youtube: "",
      instagram: "",
      discord: "",
      facebook: "",
    }
  ];

  for (const gMember of guildMembers) {
    await prisma.guildMember.upsert({
      where: { uid: gMember.uid },
      update: gMember,
      create: gMember,
    });
  }
  console.log(`✅ ${guildMembers.length} guild members created`);

  console.log("🐉 Database seeding complete!");

}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
